### PR TITLE
apply linter with `npm run lint:fix`

### PR DESCRIPTION
**Pull request by jp-ryuji**
Made sure the server is up and running on `npm run dev`.
No console error is shown on the start up (as I've seen here: https://github.com/chatch/stellarexplorer/pull/546 ).
Quickly navigated some pages on http://publicnet.local:3000/ locally and they looked fine.

There are still some formatting issues that can't be fixed automatically as follows.
I left them for now.
So github actions can't be set up now.

```
$ npm run lint
: 
✖ 57 problems (6 errors, 51 warnings)
  0 errors and 1 warning potentially fixable with the `--fix` option.
```

### CODE REVIEW

**Review by chatch — APPROVED** [review]
looks good. it's nice to have everything formatted to the same rules so let's merge this anyway. can look at those remaining errors in time. 

are they tricky to correct?

**Comment by chatch** [comment]
@jp-ryuji i pushed a change to service-worker.js. checkout the comma in there. it's fine to disable this rule there and that clears up 5 of the errors

**Comment by chatch** [comment]
fixed remaining error too.

**Comment by jp-ryuji** [comment]
This PR was superseded by https://github.com/chatch/stellarexplorer/pull/549

**Pull request closed without merging**
