### PR TITLE
Japanese menu translation completed

### PR DESCRIPTION
**Pull request by efishdew**
There are a lot of specialized terms, and I don't know if I'm translating them correctly. The "Ops" in line 109, I don't understand what it means, so I left it as it is.

### CODE REVIEW

**Comment by chatch** [comment]
> There are a lot of specialized terms, and I don't know if I'm translating them correctly. The "Ops" in line 109, I don't understand what it means, so I left it as it is.

Ops is short for "Operations". In Stellar a transaction is made up of a number of Operations. In english it was shortened to fit better. But that may not be necessary in Japanese?

**Comment by efishdew** [comment]
I see, I just need to translate it as "operation". There is no such abbreviation in Japanese.

**Comment by efishdew** [comment]
The "Ops" in line 109, Revised.

**Comment by chatch** [comment]
thank you for this contribution! I've merged it and I'll deploy it soon.

**Comment by chatch** [comment]
@efishdew FYI this has been released to steexp.com now. Please check it looks okay. Thank you for the contribution!

**Pull request merged**
