### PR TITLE
toggle color themes

### PR DESCRIPTION
**Pull request by jp-ryuji**
- The icons were got from [bootstrap icons](https://icons.getbootstrap.com/).
- The theme a user selected is saved in the local storage.
- I tried to attach a video. But it was so big that I couldn't attach it.

### CODE REVIEW

**Review by chatch — CHANGES_REQUESTED** [review]
nice! amazing to see this. a couple of things:
- can light mode be the default?
- when you mouse over the icon the cursor doesn't change but it does for the language and network selectors. can you make the cursor change on hover over the dark/light icon too?
- grey text is a little light. can you change it to black? or the shade that is in the search box looks fine so replicate that

**Comment by jp-ryuji** [comment]
@chatch 

Fixed the conflict and made some changes (defaults to light theme and fix invisible parts ...).

**Comment by chatch** [comment]
> @chatch
> 
> Fixed the conflict and made some changes (defaults to light theme and fix invisible parts ...).

looking better. noticed a case of white clipboard icon again:

image

**Comment by chatch** [comment]
> > @chatch
> > Fixed the conflict and made some changes (defaults to light theme and fix invisible parts ...).
> 
> looking better. noticed a case of white clipboard icon again:
> 
> image

same for server.toml popup view ...

**Comment by jp-ryuji** [comment]
@chatch 

Mainly fixed the "open new window" icon on the light theme, but also added the following changes, which I personally thought were a bit clumsy on the light theme.

- title on the `Set Custom Network` modal
- the links under `More` in the menu
- the options under the language selector

**Review by chatch — APPROVED** [review]

**Pull request merged**
