### PR TITLE
Traditional Chinese menu translation completed

### PR DESCRIPTION
**Pull request by efishdew**
There are a lot of specialized terms, and I don't know if I'm translating them correctly. The "Ops" in line 109, I don't understand what it means, so I left it as it is.

### CODE REVIEW

**Comment by chatch** [comment]
> There are a lot of specialized terms, and I don't know if I'm translating them correctly. The "Ops" in line 109, I don't understand what it means, so I left it as it is.

actually there is already a simplified 简体字 translation here: https://github.com/chatch/stellarexplorer/blob/master/src/languages/zh.json  So I think you can use that as a base. In most cases just translating to traditional characters is probably enough?

**Comment by efishdew** [comment]
I just did the conversion based on that Simplified Chinese file, and most of the time the expressions are similar, only some special words are expressed differently. But since the fonts are completely different, Chinese usually has a menu of two languages. "Simplified Chinese" and "Traditional Chinese".

**Comment by chatch** [comment]
thank you for this contribution! I've merged it and I'll deploy it soon.

**Comment by chatch** [comment]
@efishdew FYI this has been released to steexp.com now. Please check it looks okay. Thank you for the contribution!

**Pull request merged**
