### PR TITLE
support muxed accounts - cap-0027

### PR DESCRIPTION
**Pull request by chatch**
Support Muxed Accounts:
- show muxed AND public address when rendering accounts if muxed address information is available
- search by muxed address
- /account/&lt;muxed address&gt;

### CODE REVIEW

**Review by Hieuhuynh98 — COMMENTED** [review]
a828cc44cdc57fcaf36b3c52d4f49b975e055545

**Review by Hieuhuynh98 — COMMENTED** [review]
use stellar-sdk StrKey.isValidMed25519PublicKey for proper detection of muxed address
refactor account - handle 3 types of addresses cleanly
 master

**Comment by Idowas1** [comment]
I need your number so you can lead me through

**Comment by HTC37** [comment]
gh pr checkout 314

**Pull request merged**
