### PR TITLE
Stellar explorer ui improvements

### PR DESCRIPTION
**Pull request by stellarstyler**
Update steexp ui scheme from this:

screen shot 2018-02-08 at 9 38 14 pm

To this:

screen shot 2018-02-08 at 9 37 55 pm

### CODE REVIEW

**Comment by chatch** [comment]
looks great @stellarstyler !   i'll take a look at this soon.

**Comment by stellarstyler** [comment]
Sounds good 👍

**Comment by chatch** [comment]
yeah awesome. it looks A LOT better!

**Comment by chatch** [comment]
@stellarstyler I finally deployed this so new styles are live. Took a while as I had issues with another change I'd released with it and also busy with chinese new year. :)  

btw. I'll be entering the project into the Stellar Build Challenge again so send me a Stellar public address and I'll send you some Lumens if the project gets awarded some. Cheers.

**Comment by stellarstyler** [comment]
Awesome @chatch! Can't wait to see it and hope the challenge goes well. I'll look into making some more improvements in the next couple weeks as well. Here's my address too: GB6DN2NHF4OCCU53TGGENDMWNELWMNW2DJVY6XR4NFG4LB3MVDSQE2SG

**Pull request merged**
