### PR TITLE
 French translation

### PR DESCRIPTION
**Pull request by alexouille123**
I haven't finished translating it yet but here is the french translations file !

### CODE REVIEW

**Comment by HoussemKMod** [comment]
Salut, tu serais dispo sur Discord ?je t'invite à me contacter via HoussemK#6643

**Comment by chatch** [comment]
> I haven't finished translating it yet but here is the french translations file !

great thank you @alexouille123 !  I will merge and deploy this in the next week or so.

**Comment by chatch** [comment]
thank you for this contribution! I've merged it and I'll deploy it soon.

**Comment by chatch** [comment]
@alexouille123 FYI this has been released to steexp.com now. Please check it looks okay. Thank you for the contribution!

**Pull request merged**
