### PR TITLE
sketch out some sample graphs with graph.js

### PR DESCRIPTION
**Pull request by Edisontravis**
Files change

### CODE REVIEW

**Comment by chatch** [comment]
very late to this as i get a lot of spam PRs and issues.

if this is still valid could you explain what these graphs are for. thanks.

**Comment by Capojazzy1** [comment]
#335

**Comment by haticecan37** [comment]
gh pr checkout 335

**Review by Dezzj — COMMENTED** [review]
Veiwed

**Comment by Thompson1985** [comment]
Veiwed

**Review by Dezzj — COMMENTED** [review]
Veiwed

**Review by Dezzj — COMMENTED** [review]
Veiwed

**Review by haticecan37 — APPROVED** [review]

**Review by haticecan37 — APPROVED** [review]
package.json

**Pull request closed without merging**
