### PR TITLE
Add CSV export feature

### PR DESCRIPTION
**Pull request by cmichi**
Hi @chatch,

I have implemented the feature from #67 in this PR. Can you please take a look at it? (This is the first time I have worked with react.)

Note: An issue in the horizon server regarding pagination of trades was fixed lately (https://github.com/stellar/go/issues/530). This fix is not yet deployed to the testnet though, so if the trades export behaves strangely this is the reason.

### CODE REVIEW

**Comment by chatch** [comment]
looks great @cmichi!  i like how it shows the status as it's fetching the chunks of records. works really well.

a couple of things:

from the top level views (ie. transactions, payments, etc. from the nav bar menus) there is no limit on export so it will keep downloading until it reaches genesis.  we should put a limit on export from these views.  maybe 1000 records?

for the download, a content-type of text/csv would be better than text/plain so the browsers can suggest some csv handling app.

with the trades bug, does it mean there will be duplicates in the result? i think it's fine anyways, once the horizon fix is deployed it'll behave as it should.

**Comment by cmichi** [comment]
Hi there @chatch,

thanks for the remarks!

I have amended the PR to contain a hard limit of 20k. I chose this number because the export for that many records still works very well on my (pretty standard) machine and since I could easily find accounts with e.g. a couple thousand operations. So 20k sounds like a reasonable compromise to me. Let me know if you think otherwise.

I also changed the content-type to `text/csv`, good point!

Regarding the horizon bug for trades: yes, duplicates are a possibility, but I agree that it shouldn't be much of a concern, since it seems to be deployed soon.

**Comment by chatch** [comment]
great stuff. I'll merge this now.

**Comment by cmichi** [comment]
Awesome, thanks!

**Pull request merged**
